# Generated by Django 4.1.2 on 2023-09-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_position', models.IntegerField(default=0)),
                ('stay_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_position_x', models.IntegerField(default=0)),
                ('click_position_y', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_scroll_position', models.IntegerField(default=0)),
                ('max_scroll_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Url_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='ユーザー名')),
                ('web_site', models.URLField(blank=True)),
                ('attention_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lpanalysis.attentiondata')),
                ('click_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lpanalysis.clickdata')),
                ('scroll_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lpanalysis.scrolldata')),
            ],
        ),
    ]
